Imports System
Imports System.Runtime.InteropServices
Imports System.Windows.Forms

Namespace Examples
    Partial Public Class Form1
        Inherits Form

        Private _application As SolidEdgeFramework.Application
        Private _window As SolidEdgeFramework.Window
        Private _view As SolidEdgeFramework.View
        Private _animationEvents As SolidEdgeFramework.ISEAnimationEvents_Event

        Public Sub New()
            InitializeComponent()
        End Sub

        Private Sub Form1_Load(ByVal sender As Object, ByVal e As EventArgs)
            ' Connect to a running instance of Solid Edge.
            _application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)

            ' A 3D document must be open.
            _window = CType(_application.ActiveWindow, SolidEdgeFramework.Window)
            _view = _window.View

            ' Connect to events using delegate event model.
            _animationEvents = CType(_view.AnimationEvents, SolidEdgeFramework.ISEAnimationEvents_Event)

            ' Attach to specific events.
            AddHandler _animationEvents.AnimationEvent, AddressOf _animationEvents_AnimationEvent
        End Sub

        Private Sub _animationEvents_AnimationEvent(ByVal AnimationEventType As SolidEdgeFramework.AnimationEventConstants, ByVal nFrame As Integer)
            ' Handle AnimationEvent.
        End Sub

        Private Sub Form1_FormClosing(ByVal sender As Object, ByVal e As FormClosingEventArgs)
            If _animationEvents IsNot Nothing Then
                ' Dettach from specific events.
                RemoveHandler _animationEvents.AnimationEvent, AddressOf _animationEvents_AnimationEvent
            End If

            _animationEvents = Nothing
            _application = Nothing
        End Sub
    End Class
End Namespace