Option Infer On

Imports System
Imports System.Collections.Generic
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim documents As SolidEdgeFramework.Documents = Nothing
            Dim draftDocument As SolidEdgeDraft.DraftDocument = Nothing
            Dim sheet As SolidEdgeDraft.Sheet = Nothing
            Dim featureControlFrames As SolidEdgeFrameworkSupport.FeatureControlFrames = Nothing
            Dim featureControlFrame As SolidEdgeFrameworkSupport.FeatureControlFrame = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                documents = application.Documents
                draftDocument = CType(documents.Add("SolidEdge.DraftDocument"), SolidEdgeDraft.DraftDocument)
                sheet = draftDocument.ActiveSheet
                featureControlFrames = CType(sheet.FeatureControlFrames, SolidEdgeFrameworkSupport.FeatureControlFrames)

                featureControlFrame = featureControlFrames.Add(0.1, 0.1, 0)
                featureControlFrame.PrimaryFrame = "%FL%VB0.001%MC%VBA"
                featureControlFrame.AddVertex(0.2, 0.2, 0)

                Dim name = featureControlFrame.Name
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace