Option Infer On

Imports System
Imports System.Collections.Generic
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim documents As SolidEdgeFramework.Documents = Nothing
            Dim draftDocument As SolidEdgeDraft.DraftDocument = Nothing
            Dim sheet As SolidEdgeDraft.Sheet = Nothing
            Dim centerMarks As SolidEdgeFrameworkSupport.CenterMarks = Nothing
            Dim centerMark1 As SolidEdgeFrameworkSupport.CenterMark = Nothing
            Dim centerMark2 As SolidEdgeFrameworkSupport.CenterMark = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                documents = application.Documents
                draftDocument = CType(documents.Add("SolidEdge.DraftDocument"), SolidEdgeDraft.DraftDocument)
                sheet = draftDocument.ActiveSheet
                centerMarks = CType(sheet.CenterMarks, SolidEdgeFrameworkSupport.CenterMarks)

                centerMark1 = centerMarks.Add(0.25, 0.25, 0)
                centerMark2 = centerMarks.Add(0.3, 0.3, 0)

                Dim zOrder = centerMark2.ZOrder

                centerMark2.SendBackward()

                zOrder = centerMark2.ZOrder
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace