Option Infer On

Imports System
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim assemblyDocument As SolidEdgeAssembly.AssemblyDocument = Nothing
            Dim physicalProperties As SolidEdgeAssembly.PhysicalProperties = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                assemblyDocument = TryCast(application.ActiveDocument, SolidEdgeAssembly.AssemblyDocument)

                If assemblyDocument IsNot Nothing Then
                    physicalProperties = assemblyDocument.PhysicalProperties

                    physicalProperties.UserDefinedPropertiesStatus = True

                    Dim Volume As Double = 0.135
                    Dim Area As Double = 57
                    Dim Mass As Double = 5
                    Dim CenterOfMass = CType(New Double(), System.Array) { 15, 0.5, 5 }
                    Dim CenterOfVolume = CType(New Double(), System.Array) { 35, 0.05, 53 }
                    Dim GlobalMoments = CType(New Double(), System.Array) { 1, 4, 3, 5, 8, 7, 9 }
                    Dim PrincipalMoments = CType(New Double(), System.Array) { 4, 3, 5 }
                    Dim PrincipalAxis1 = CType(New Double(), System.Array) { 3, 9, 5 }
                    Dim PrincipalAxis2 = CType(New Double(), System.Array) { 7, 5, 6 }
                    Dim PrincipalAxis3 = CType(New Double(), System.Array) { 5, 8, 5 }
                    Dim RadiiOfGyration = CType(New Double(), System.Array) { 1, 5, 2 }
                    Dim OverrideMass As Double = 15

                    physicalProperties.SetUserDefinedAssemblyPhysicalProperties(Volume, Area, Mass, CenterOfMass, CenterOfVolume, GlobalMoments, PrincipalMoments, PrincipalAxis1, PrincipalAxis2, PrincipalAxis3, RadiiOfGyration, OverrideMass)
                End If
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace