Imports System
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim document As SolidEdgeFramework.SolidEdgeDocument = Nothing
            Dim variables As SolidEdgeFramework.Variables = Nothing
            Dim variable As SolidEdgeFramework.variable = Nothing
            Dim variableList As SolidEdgeFramework.VariableList = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)

                document = CType(application.ActiveDocument, SolidEdgeFramework.SolidEdgeDocument)

                variables = CType(document.Variables, SolidEdgeFramework.Variables)

                Dim pFindCriterium As String = "*"
                Dim NamedBy As Object = SolidEdgeConstants.VariableNameBy.seVariableNameByBoth
                Dim VarType As Object = SolidEdgeConstants.VariableVarType.SeVariableVarTypeBoth
                Dim CaseInsensitive As Object = False

                ' Execute query.
                variableList = CType(variables.Query(pFindCriterium, NamedBy, VarType, CaseInsensitive), SolidEdgeFramework.VariableList)

                ' Add a new variable after the initial query.
                variable = CType(variables.Add("Test", "100.0", SolidEdgeConstants.UnitTypeConstants.igUnitDistance), SolidEdgeFramework.variable)

                ' Add the new variable to the VariableList.
                variableList.Add(variable)

                For i As Integer = 1 To variableList.Count
                    Dim item = variableList.Item(i)

                    ' Determine the runtime type of the object.
                    Dim itemType = item.GetType()
                    Dim objectType = CType(itemType.InvokeMember("Type", System.Reflection.BindingFlags.GetProperty, Nothing, item, Nothing), SolidEdgeFramework.ObjectType)

                    Select Case objectType
                        Case SolidEdgeFramework.ObjectType.igDimension
                            Dim dimension = CType(item, SolidEdgeFrameworkSupport.Dimension)
                        Case SolidEdgeFramework.ObjectType.igVariable
                            variable = CType(item, SolidEdgeFramework.variable)
                    End Select
                Next i
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace