Option Infer On

Imports System
Imports System.Collections.Generic
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim partDocument As SolidEdgePart.PartDocument = Nothing
            Dim models As SolidEdgePart.Models = Nothing
            Dim model As SolidEdgePart.Model = Nothing
            Dim helixCutouts As SolidEdgePart.HelixCutouts = Nothing
            Dim helixCutout As SolidEdgePart.HelixCutout = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                partDocument = TryCast(application.ActiveDocument, SolidEdgePart.PartDocument)

                If partDocument IsNot Nothing Then
                    models = partDocument.Models
                    model = models.Item(1)
                    helixCutouts = model.HelixCutouts

                    For i As Integer = 1 To helixCutouts.Count
                        helixCutout = helixCutouts.Item(i)

                        Dim x1 As Double = Nothing
                        Dim y1 As Double = Nothing
                        Dim Z1 As Double = Nothing
                        Dim x2 As Double = Nothing
                        Dim y2 As Double = Nothing
                        Dim Z2 As Double = Nothing

                        helixCutout.Range(x1, y1, Z1, x2, y2, Z2)
                    Next i
                End If
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace