Option Infer On

Imports System
Imports System.Collections.Generic
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim documents As SolidEdgeFramework.Documents = Nothing
            Dim draftDocument As SolidEdgeDraft.DraftDocument = Nothing
            Dim sheet As SolidEdgeDraft.Sheet = Nothing
            Dim boundaries2d As SolidEdgeFrameworkSupport.Boundaries2d = Nothing
            Dim boundary2d As SolidEdgeFrameworkSupport.Boundary2d = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                documents = application.Documents
                draftDocument = CType(documents.Add("SolidEdge.DraftDocument"), SolidEdgeDraft.DraftDocument)
                sheet = draftDocument.ActiveSheet
                boundaries2d = CType(sheet.Boundaries2d, SolidEdgeFrameworkSupport.Boundaries2d)

                Dim Points = CType(New Double(), System.Array) { 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.1 }

                boundary2d = boundaries2d.AddByPoints(Points.Length \ 2, Points)

                boundary2d.Move(0, 0, 0.05, 0.05)
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace