Imports System.Runtime.InteropServices

Public Class Form1

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim objApp As SolidEdgeFramework.Application
        Dim objDoc As SolidEdgeDraft.DraftDocument
        Dim objSheet As SolidEdgeDraft.Sheet
        Dim objDrawingViews As SolidEdgeDraft.DrawingViews
        Dim objDrawingView As SolidEdgeDraft.DrawingView
        Dim objViewDefaultEdgeStyleName As String

        Try
            objApp = Marshal.GetActiveObject("SolidEdge.Application")
			'Open draft file containing views
            objDoc = objApp.ActiveDocument()
            objSheet = objDoc.ActiveSheet
            objDrawingViews = objSheet.DrawingViews
            objDrawingView = objDrawingViews(1)

            objViewDefaultEdgeStyleName = objDrawingView.Defaults_CoordinateSystemEdgeStyleName()

            objDrawingView.Defaults_CoordinateSystemEdgeStyleName() = "Hidden"

        Catch ex As Exception
            MsgBox(ex.ToString)
            Clipboard.SetText(ex.ToString)
        End Try

    End Sub

End Class
