Option Infer On

Imports System
Imports System.Collections.Generic
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim documents As SolidEdgeFramework.Documents = Nothing
            Dim draftDocument As SolidEdgeDraft.DraftDocument = Nothing
            Dim sheet As SolidEdgeDraft.Sheet = Nothing
            Dim complexStrings2d As SolidEdgeFrameworkSupport.ComplexStrings2d = Nothing
            Dim complexString2d1 As SolidEdgeFrameworkSupport.ComplexString2d = Nothing
            Dim complexString2d2 As SolidEdgeFrameworkSupport.ComplexString2d = Nothing
            Dim lines2d As SolidEdgeFrameworkSupport.Lines2d = Nothing
            Dim line2d1 As SolidEdgeFrameworkSupport.Line2d = Nothing
            Dim line2d2 As SolidEdgeFrameworkSupport.Line2d = Nothing
            Dim line2d3 As SolidEdgeFrameworkSupport.Line2d = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                documents = application.Documents
                draftDocument = CType(documents.Add("SolidEdge.DraftDocument"), SolidEdgeDraft.DraftDocument)
                sheet = draftDocument.ActiveSheet
                lines2d = sheet.Lines2d
                complexStrings2d = sheet.ComplexStrings2d

                line2d1 = lines2d.AddBy2Points(0.1, 0.1, 0.2, 0.2)
                line2d2 = lines2d.AddBy2Points(0.2, 0.2, 0.4, 0.2)
                line2d3 = lines2d.AddBy2Points(0.4, 0.2, 0.5, 0.1)

                Dim members = DirectCast(New Object(), System.Array) { line2d1, line2d2, line2d3 }

                complexString2d1 = complexStrings2d.AddByObjects(members.Length, members)

                complexString2d2 = CType(complexString2d1.Duplicate(0.075, 0.125), SolidEdgeFrameworkSupport.ComplexString2d)

                Dim zOrder = complexString2d1.ZOrder

                complexString2d1.BringForward()

                zOrder = complexString2d1.ZOrder
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace