Imports System.Runtime.InteropServices

Public Class Form1

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim objSEApplication As SolidEdgeFramework.Application = Nothing
        Dim objDoc As SolidEdgePart.SheetMetalDocument = Nothing

        Try
            ' Create/get the application with specific settings
            objSEApplication = Marshal.GetActiveObject("SolidEdge.Application")

            'Get the active document.
            objDoc = objSEApplication.ActiveDocument()

            If objDoc.OrderedBodyInSyncVisible = True Then
                MsgBox("Ordered body status in sync is visible")
                'Change the status to hidden if visible
                objDoc.OrderedBodyInSyncVisible = False
            Else
                MsgBox("Ordered body status in sync is hidden")
                'Change the status to visible if hidden
                objDoc.OrderedBodyInSyncVisible = True
            End If
            'Refresh view
            objSEApplication.StartCommand(SolidEdgeFramework.SolidEdgeCommandConstants.seRefreshViewCommand)


        Catch ex As Exception
            MsgBox(ex.ToString)
        End Try
    End Sub
End Class
