Imports System
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim draftDocument As SolidEdgeDraft.DraftDocument = Nothing
            Dim modelLinks As SolidEdgeDraft.ModelLinks = Nothing
            Dim modelLink As SolidEdgeDraft.ModelLink = Nothing
            Dim modelDocument As SolidEdgeFramework.SolidEdgeDocument = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                draftDocument = TryCast(application.ActiveDocument, SolidEdgeDraft.DraftDocument)

                If draftDocument IsNot Nothing Then
                    modelLinks = draftDocument.ModelLinks

                    For i As Integer = 1 To modelLinks.Count
                        modelLink = modelLinks.Item(i)
                        modelLink.UpdateViews()
                    Next i
                End If
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace