---
uid: SolidEdgeFrameworkSupport.Arcs2d.AddByCenterStartEnd(System.Double,System.Double,System.Double,System.Double,System.Double,System.Double)
summary: 
remarks: 
syntax:
    parameters:
    - id: xCenter
      description: Specifies the coordinates of the center point of the arc.
    - id: xEnd
      description: Specifies the coordinates of the end point of the arc.
    - id: xStart
      description: Specifies the coordinates of the start point of the arc.
    - id: yCenter
      description: Specifies the coordinates of the center point of the arc.
    - id: yEnd
      description: Specifies the coordinates of the end point of the arc.
    - id: yStart
      description: Specifies the coordinates of the start point of the arc.
example: [*content]
---
[!code-vb[Main](..\snippets\SolidEdgeFrameworkSupport.Arcs2d.AddByCenterStartEnd.vb]
[!code-csharp[Main](..\snippets\SolidEdgeFrameworkSupport.Arcs2d.AddByCenterStartEnd.cs]
