Option Infer On

Imports System
Imports System.Collections.Generic
Imports System.Runtime.InteropServices

Namespace Examples
    Friend Class Program
        <STAThread>
        Shared Sub Main(ByVal args() As String)
            Dim application As SolidEdgeFramework.Application = Nothing
            Dim documents As SolidEdgeFramework.Documents = Nothing
            Dim partDocument As SolidEdgePart.PartDocument = Nothing
            Dim refPlanes As SolidEdgePart.RefPlanes = Nothing
            Dim profileSets As SolidEdgePart.ProfileSets = Nothing
            Dim profileSet As SolidEdgePart.ProfileSet = Nothing
            Dim profiles As SolidEdgePart.Profiles = Nothing
            Dim profile As SolidEdgePart.Profile = Nothing
            Dim relations2d As SolidEdgeFrameworkSupport.Relations2d = Nothing
            Dim relation2d As SolidEdgeFrameworkSupport.Relation2d = Nothing
            Dim circles2d As SolidEdgeFrameworkSupport.Circles2d = Nothing
            Dim circle2d1 As SolidEdgeFrameworkSupport.Circle2d = Nothing
            Dim circle2d2 As SolidEdgeFrameworkSupport.Circle2d = Nothing

            Try
                ' See "Handling 'Application is Busy' and 'Call was Rejected By Callee' errors" topic.
                OleMessageFilter.Register()

                ' Attempt to connect to a running instance of Solid Edge.
                application = DirectCast(Marshal.GetActiveObject("SolidEdge.Application"), SolidEdgeFramework.Application)
                documents = application.Documents
                partDocument = CType(documents.Add("SolidEdge.PartDocument"), SolidEdgePart.PartDocument)
                refPlanes = partDocument.RefPlanes
                profileSets = partDocument.ProfileSets
                profileSet = profileSets.Add()
                profiles = profileSet.Profiles
                profile = profiles.Add(refPlanes.Item(1))
                relations2d = CType(profile.Relations2d, SolidEdgeFrameworkSupport.Relations2d)
                circles2d = profile.Circles2d

                circle2d1 = circles2d.AddByCenterRadius(0, 0, 0.1)
                circle2d2 = circles2d.AddByCenterRadius(0.05, 0.05, 0.12)

                relation2d = relations2d.AddConcentric(circle2d1, circle2d2)
            Catch ex As System.Exception
                Console.WriteLine(ex)
            Finally
                OleMessageFilter.Unregister()
            End Try
        End Sub
    End Class
End Namespace